code-insiders --install-extension 42Crunch.vscode-openapi
code-insiders --install-extension amazonwebservices.aws-toolkit-vscode
code-insiders --install-extension anseki.vscode-color
code-insiders --install-extension bbenoist.vagrant
code-insiders --install-extension bceskavich.theme-dracula-at-night
code-insiders --install-extension cobaltblu27.rainbow-highlighter
code-insiders --install-extension codezombiech.gitignore
code-insiders --install-extension cssho.vscode-svgviewer
code-insiders --install-extension dbaeumer.vscode-eslint
code-insiders --install-extension dracula-theme.theme-dracula
code-insiders --install-extension EditorConfig.EditorConfig
code-insiders --install-extension esbenp.prettier-vscode
code-insiders --install-extension formulahendry.auto-close-tag
code-insiders --install-extension formulahendry.auto-rename-tag
code-insiders --install-extension GitHub.copilot
code-insiders --install-extension Gruntfuggly.todo-tree
code-insiders --install-extension hashicorp.hcl
code-insiders --install-extension hashicorp.terraform
code-insiders --install-extension IBM.output-colorizer
code-insiders --install-extension jakebathman.mysql-syntax
code-insiders --install-extension JuanBlanco.solidity
code-insiders --install-extension mechatroner.rainbow-csv
code-insiders --install-extension mgmcdermott.vscode-language-babel
code-insiders --install-extension mhutchie.git-graph
code-insiders --install-extension mikestead.dotenv
code-insiders --install-extension mindaro-dev.file-downloader
code-insiders --install-extension ms-azuretools.vscode-docker
code-insiders --install-extension ms-dotnettools.vscode-dotnet-runtime
code-insiders --install-extension ms-vscode-remote.remote-containers
code-insiders --install-extension ms-vscode.azure-account
code-insiders --install-extension ms-vscode.cmake-tools
code-insiders --install-extension ms-vscode.cpptools
code-insiders --install-extension oderwat.indent-rainbow
code-insiders --install-extension rangav.vscode-thunder-client
code-insiders --install-extension redhat.fabric8-analytics
code-insiders --install-extension redhat.vscode-commons
code-insiders --install-extension redhat.vscode-xml
code-insiders --install-extension redhat.vscode-yaml
code-insiders --install-extension rogalmic.bash-debug
code-insiders --install-extension RReverser.llvm
code-insiders --install-extension Rubymaniac.vscode-paste-and-indent
code-insiders --install-extension styled-components.vscode-styled-components
code-insiders --install-extension timonwong.shellcheck
code-insiders --install-extension tombonnike.vscode-status-bar-format-toggle
code-insiders --install-extension tomoki1207.pdf
code-insiders --install-extension trufflesuite-csi.truffle-vscode
code-insiders --install-extension twxs.cmake
code-insiders --install-extension vscode-icons-team.vscode-icons
code-insiders --install-extension waderyan.gitblame
code-insiders --install-extension xyz.plsql-language
