code --install-extension 42Crunch.vscode-openapi
code --install-extension adpyke.vscode-sql-formatter
code --install-extension anseki.vscode-color
code --install-extension bbenoist.vagrant
code --install-extension bceskavich.theme-dracula-at-night
code --install-extension codezombiech.gitignore
code --install-extension cssho.vscode-svgviewer
code --install-extension dracula-theme.theme-dracula
code --install-extension EditorConfig.EditorConfig
code --install-extension GitHub.copilot
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.hcl
code --install-extension hashicorp.terraform
code --install-extension IBM.output-colorizer
code --install-extension jakebathman.mysql-syntax
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension mindaro-dev.file-downloader
code --install-extension ms-vscode-remote.remote-containers
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension Rubymaniac.vscode-paste-and-indent
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension stkb.rewrap
code --install-extension timonwong.shellcheck
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension tomoki1207.pdf
code --install-extension vscode-icons-team.vscode-icons
code --install-extension xyz.plsql-language
